### ISSUE TITLE
Are 'Custom Validators' a good fit for this repo?

### ISSUE THREAD

**Issue by tyler-8** [netbox-community/reports#76]
I have some CustomValidators that I suspect would be useful to others, how do the maintainers & community feel about about a new folder called "custom_validators" in this repo?

**Comment by ryanmerolle** [comment]
Yes.  We have long discussed renaming this repo.  Maybe netbox-extensibility?

export templates also make sense here.

**Comment by danner26** [comment]
I would agree with @ryanmerolle, I think renaming this repo to something along the lines of `netbox-extensibility`, `netbox-extensions`, `netbox-enhancements`, `netbox-expansions`, `netbox-add-ons` or something similar would make sense

**Comment by ryanmerolle** [comment]
The maintainer team already said they were fine with including the various scripts to this repo.  We just need to settle on a rename.
Since the docs call these features [customization](https://docs.netbox.dev/en/stable/customization/custom-validation/), we could also try that name.


So we will add directories for:

- custom_validators
- export_templates
- custom_links (a markdown of jinja logic for linking to other tools like monitoring)
- Am I missing anything?

**Comment by danner26** [comment]
In my opinion, `netbox-customizations` sounds like a winner then; especially if the documentation already refers to them as such

**Comment by danner26** [comment]
Is there any reason that the single powershell script in `other` folder does not live within the `scripts` folder?

**Comment by ryanmerolle** [comment]
everything we mentioned and everything included in the repo already is a very specific netbox customization that is defined in the documentation and uploaded to a netbox server to be run by netbox.  The Powershell script is not.  We can either place it in a better named directory or remove it.

**Comment by tyler-8** [comment]
Closing since I added validators in #78 - I'll leave the repo re-naming to the maintainer's discretion

**Comment by danner26** [comment]
I will leave that completely up to @ryanmerolle 😄

**Comment by ryanmerolle** [comment]
I'm cool with whatever name just need to tell the other maintainers before doing it and need an admin to make the change.  I think `netbox-customizations` makes sense.
